openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /products/:
    get:
      operationId: products_retrieve
      description: |-
        _summary_
        Simple ViewSets for Viewing the Categories
      tags:
      - products
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: products_create
      description: |-
        _summary_
        Simple ViewSets for Viewing the Categories
      tags:
      - products
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
